# Generated by Django 4.2.30 on 2026-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('objective', models.CharField(choices=[('LEAD_GENERATION', 'Lead Generation'), ('TRAFFIC', 'Traffic'), ('ENGAGEMENT', 'Engagement')], default='LEAD_GENERATION', max_length=30)),
                ('audience', models.CharField(max_length=120)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('response_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
